parameters:
    phpbbmodders.sfscompanion.tables.honeypot_trips: '%core.table_prefix%sfsc_honeypot_trips'

services:
    phpbbmodders.sfscompanion.core.functions:
        class: phpbbmodders\sfscompanion\core\functions
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@template'
            - '@request'
            - '@config'
            - '@auth'
            - '@phpbbmodders.stopforumspam.core.sfsapi'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbbmodders.sfscompanion.controller.finder:
        class: phpbbmodders\sfscompanion\controller\finder
        arguments:
            - '@template'
            - '@request'
            - '@controller.helper'
            - '@user'
            - '@auth'
            - '@phpbbmodders.sfscompanion.core.functions'

    phpbbmodders.sfscompanion.listener:
        class: phpbbmodders\sfscompanion\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@auth'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    phpbbmodders.sfscompanion.cron.task.prune_logs:
        class: phpbbmodders\sfscompanion\cron\task\prune_logs
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@log'
        calls:
            - [set_name, [cron.task.phpbbmodders.sfscompanion.prune_logs]]
        tags:
            - { name: cron.task }

    phpbbmodders.sfscompanion.honeypot_listener:
        class: phpbbmodders\sfscompanion\event\honeypot_listener
        arguments:
            - '@config'
            - '@request'
            - '@user'
            - '@language'
            - '@dbal.conn'
            - '@notification_manager'
            - '@auth'
            - '@template'
            - '%phpbbmodders.sfscompanion.tables.honeypot_trips%'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    phpbbmodders.sfscompanion.notification.type.honeypot_restricted:
        class: phpbbmodders\sfscompanion\notification\type\honeypot_restricted
        parent: notification.type.base
        shared: false
        tags: [{ name: notification.type }]
        calls:
            - ['set_user_loader', ['@user_loader']]

    phpbbmodders.sfscompanion.cron.task.prune_honeypot_trips:
        class: phpbbmodders\sfscompanion\cron\task\prune_honeypot_trips
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%phpbbmodders.sfscompanion.tables.honeypot_trips%'
        calls:
            - [set_name, [cron.task.phpbbmodders.sfscompanion.prune_honeypot_trips]]
        tags:
            - { name: cron.task }
