services:
    phpbbmodders.sfscompanion.core.functions:
        class: phpbbmodders\sfscompanion\core\functions
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@template'
            - '@request'
            - '@config'
            - '@auth'
            - '@rmcgirr83.stopforumspam.core.sfsapi'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbbmodders.sfscompanion.controller.finder:
        class: phpbbmodders\sfscompanion\controller\finder
        arguments:
            - '@template'
            - '@request'
            - '@controller.helper'
            - '@user'
            - '@auth'
            - '@phpbbmodders.sfscompanion.core.functions'

    phpbbmodders.sfscompanion.listener:
        class: phpbbmodders\sfscompanion\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@auth'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    phpbbmodders.sfscompanion.cron.task.prune_logs:
        class: phpbbmodders\sfscompanion\cron\task\prune_logs
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@log'
        calls:
            - [set_name, [cron.task.phpbbmodders.sfscompanion.prune_logs]]
        tags:
            - { name: cron.task }
